### ISSUE TITLE
Square brackets are reserved in Polygon

### ISSUE THREAD

**Issue by aleexf** [alex65536/parmpars#1]
It's impossible to pass ranges as command line argument when stressing solutions in **Polygon**, because characters of square brackets are reserved.

**Comment by aleexf** [comment]
It's possible to init range by one value

**Comment by alex65536** [comment]
Why close it? It's a valid issue and worth thinking on how to fix it

**Comment by aleexf** [comment]
Really! I completely forgot that we can use one range to generate many variables. I wanted to propose to add one more syntax for ranges. For example, `variable=range(l, r)`. But here appears another one issue (or it's not an issue): generated value will depended on syntax that you using.

**Comment by alex65536** [comment]
Closing; now (1;10) also defines a range.
